### ISSUE TITLE
dsu with multipath

### ISSUE THREAD

**Issue by Klaas-** [CSC-IT-Center-for-Science/ansible-role-dell-firmware-upgrade#16]
Hi,
I am thinking about implementing multipath.conf blacklist handling in this role, would you say this is a good place for this or should it be a separate role for changing the multipath config?

Background:
https://bugzilla.redhat.com/show_bug.cgi?id=1380272
if you use multipath you need to blacklist the devices dsu uses during upgrade otherwise they'll be in use by multipath

Greetings
Klaas

**Comment by martbhell** [comment]
Hi!

I suppose some might want to use a specific role to manage multipath.

Let's add it.

I would like a conditional like:

> when: dell_firmware_upgrade_manage_multipath

Any thoughts if this should be enabled by default?

**Comment by Klaas-** [comment]
I would build a conditional that checks for active multipath I guess :)

**Comment by martbhell** [comment]
That would also be nice, but if multipath is active and already managed by some other ansible-role then I suppose there could be some conflicts or unnecessary double work?

**Comment by Klaas-** [comment]
yeah.
I'll definitely put an off switch into it -- default from my pov should be "on if multipath is running"

**Comment by martbhell** [comment]
Sound good

**Comment by Klaas-** [comment]
@martbhell What is your policy on backwards compatibility? I'm seeing a message about the deprecation of "--apply-upgrades-only" -- its now "--apply-upgrades"

I can change it with the multipathd PR but that will break older dsu versions.

**Comment by martbhell** [comment]
My policy in general is: If someone is using this role they should not use "version: master" but rather a specific release/tag/commit. Then they can upgrade dsu and this role at the same time. Fortunately it seems that the parameter is not removed yet but only deprecated. So probably changing it now  to --apply-upgrades won't be an issue until quite far in the future when I really hope someone has updated to dsu 1.6.0 :)

**Comment by Klaas-** [comment]
see #18
