### ISSUE TITLE
dell gpg changes // use --ignore-signature

### ISSUE THREAD

**Issue by Klaas-** [CSC-IT-Center-for-Science/ansible-role-dell-firmware-upgrade#19]
Hi,
dsu 1.7.0 seems to have changed the behaviour how it uses the gpg keys. Before it was enough to have the keys inside of the rpm db so yum can verify the packages. Now they put them into a gpg keyring. See discussion in http://lists.us.dell.com/pipermail/linux-poweredge/2019-May/052012.html

So I'd say we could either add --ignore-signature to defaults:
https://github.com/CSCfi/ansible-role-dell-firmware-upgrade/blob/master/defaults/main.yml#L17 

or add the rollout of those files and use --import-public-key or wait for dell to fix it

What do you guys prefer?

**Comment by oscarkraemer** [comment]
Hi Klaas-,
Thanks for opening an issue. I don't think we would accept a PR that uses the --ignore-signature. We have an open task in our jira to fix this issue, I don't know how we will solve it since the owner will get to decide. Based on your two options I think the --import-public-key is the better solution.

**Comment by Klaas-** [comment]
@oscarkraemer I would say this: you can skip the gpg check because it was already performed by yum on EL* systems. I see no reason to check it a 2nd time during dsu operation. That being said: I can supply a patch that uses import-public-key and rolls out the three keys it checks for if that is what you're looking for

**Comment by Klaas-** [comment]
https://linux.dell.com/repo/hardware/DSU_19.06.00/ dell also updated their page:

> Known Issues
> Following message displayed while running DSU 1.7.
> 
> - Unable to read public file /usr/libexec/dell_dup/0x756ba70b1019ced6.asc
> - Unable to read public file /usr/libexec/dell_dup/0x1285491434D8786F.asc
> - Unable to read public file /usr/libexec/dell_dup/0xca77951d23b66a9d.asc
> 
> Please run the following command and run the dsu again.
> curl -s https://linux.dell.com/repo/hardware/dsu/copygpgkeys.sh | bash

I would dislike to run curl and pipe it to bash :) but the idea of just shipping the keys with this ansible role may be a good start
