### ISSUE TITLE
Check mode execution failing because of gpg keys

### ISSUE THREAD

**Issue by Klaas-** [CSC-IT-Center-for-Science/ansible-role-dell-firmware-upgrade#22]
Currently check mode does not copy the gpg keys but rpm_key seems to support check mode.

It will now fail because the gpg key is not there.

Possible solutions:
* execute https://github.com/CSCfi/ansible-role-dell-firmware-upgrade/blob/master/tasks/main.yml#L33-L45 even in check mode
* do not execute https://github.com/CSCfi/ansible-role-dell-firmware-upgrade/blob/master/tasks/main.yml#L47-L51 in check mode

Which one would you prefer? I would tend to not executing rpm_key in check mode

**Comment by martbhell** [comment]
I prefer check mode to do as little as possible.

**Comment by martbhell** [comment]
For reference - the error with ansible 2.5.14:

<pre>
failed: [mycompute1.example.org] (item=0x756ba70b1019ced6.asc) => {"changed": false, "item": "0x756ba70b1019ced6.asc", "msg": "Not a valid key /usr/libexec/dell_dup/0x756ba70b1019ced6.asc"}
</pre>

https://github.com/ansible/ansible/blob/580b0138371c406ab3ce1706f9cf7ab4dd83049d/lib/ansible/modules/packaging/os/rpm_key.py#L199

**Comment by Klaas-** [comment]
you need to update your ansible :) 2.5 has been unmaintained for quite a while -- error message is same with 2.8

**Comment by martbhell** [comment]
Totally should ;)
