### ISSUE TITLE
Multipathd blacklist needs to be extended

### ISSUE THREAD

**Issue by Klaas-** [CSC-IT-Center-for-Science/ansible-role-dell-firmware-upgrade#27]
https://bugzilla.redhat.com/show_bug.cgi?id=1380272#c31

Dell seems to have changed the vendor identification for the SECUPD device. With the latest firmware it's now "Linux"

I'll PR it. Plus I read that it should be in a file in /etc/multipath/conf.d/ , rather than in main multipath.conf , I'll change that too and clean up the ansible block in multipath.conf

Expect a PR this weekend.

**Comment by junousi** [comment]
Ack
