### ISSUE TITLE
WARNING]: could not parse environment value proxy_env

### ISSUE THREAD

**Issue by martbhell** [CSC-IT-Center-for-Science/ansible-role-dell-firmware-upgrade#7]
https://github.com/CSCfi/ansible-role-dell-firmware-upgrade/blob/master/tasks/main.yml#L4

As seen in travis for these two ansible version: ansible 2.4.2.0 and ansible 2.5.0 (devel 9ed4661860) last updated 2018/01/08 14:10:54 (GMT +000)
<pre>
TASK [../ansible-role-dell-firmware-upgrade : Install Dell DSU repo] ***********
Monday 08 January 2018  14:10:36 +0000 (0:00:00.545)       0:00:01.279 ******** 
 [WARNING]: could not parse environment value, skipping:
[u'{{proxy_env|default(omit)}}']
 [WARNING]: Consider using get_url or uri module rather than running wget</pre>

**Comment by lae** [comment]
somehow landed on this issue from a google search, hey Johan :sweat_smile: 

`default({})` resolves the warning for `environment:`

**Comment by martbhell** [comment]
Hello @lae! Long time no PR :) Thank you for that hint! Seems to work as intended - made a PR about that which also improves this role a bit :)
